---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - config.playground.kot
  resources:
  - orgnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.playground.kot
  resources:
  - orgnamespaces/finalizers
  verbs:
  - update
- apiGroups:
  - config.playground.kot
  resources:
  - orgnamespaces/status
  verbs:
  - get
  - patch
  - update
