#!/bin/bash

kubectl create ns kuberoku-system
cat <<-STR | kubectl apply -n kuberoku-system -f-
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: registry
subsets:
- addresses:
  - ip: "$(getent hosts registry | awk '{ print $1 }')"
  ports:
  - name: http
    port: 5000
    protocol: TCP
STR
