# permissions for end users to edit richnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: richnamespace-editor-role
rules:
- apiGroups:
  - richns.examples.kot
  resources:
  - richnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - richns.examples.kot
  resources:
  - richnamespaces/status
  verbs:
  - get
