---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - richns.examples.kot
  resources:
  - richnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - richns.examples.kot
  resources:
  - richnamespaces/finalizers
  verbs:
  - update
- apiGroups:
  - richns.examples.kot
  resources:
  - richnamespaces/status
  verbs:
  - get
  - patch
  - update
