---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: simplecrds.k8s.example.com
spec:
  group: k8s.example.com
  names:
    kind: SimpleCRD
    listKind: SimpleCRDList
    plural: simplecrds
    shortNames:
    - simplecrd
    singular: simplecrd
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              referencedMap:
                type: string
              configMapValue:
                type: string
              secretValue:
                type: string
            required:
            - configMapValue
            - secretValue
            type: object
          status:
            properties:
              referencedValue:
                type: string
              staticValue:
                type: string
              knownConfigMapValue:
                type: string
              knownSecretValue:
                type: string
              namespaceAnnotation:
                type: string
              finalizing:
                type: boolean
            type: object
        type: object

status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
