apiVersion: config.playground.kot/v1
kind: OrgNamespace
metadata:
  name: orgnamespace-sample
spec:
  # importSecrets:
  # - name: ""
  #   namespace: ""
  #   pullCreds: true
  defaultResources:
    request:
      cpu: "500m"
      memory: "512Mi"
    limit:
      cpu: "1"
      memory: "512Mi"
