apiVersion: config.playground.kot/v1
kind: OrgNamespace
metadata:
  name: orgnamespace-sample
spec:
  importSecrets:
  # Create with `kubectl create secret generic shared-env -n default --from-literal=PLATFORM=kot`
  - name: "shared-env"
    namespace: "default"
    pullCreds: false
  defaultResources:
    request:
      cpu: "500m"
      memory: "512Mi"
    limit:
      cpu: "1"
      memory: "512Mi"
